### ISSUE TITLE
Http get request does not implement headers

### ISSUE THREAD

**Issue by SallyPickard** [BHoM/HTTP_Toolkit#25]
#### Description:
When trying to use the http adapter to access audits from the website iAuditor I get the error 'GET request failed with code Unauthorized: Unauthorized' despite entering the API token. 

#### How to replicate:
Using the test script provided the error is seen on the pull component.

#### Expected behaviour:
It should return the Json file associated with the site visit file saved on iAuditor.

#### Test file(s):

**Comment by epignatelli** [comment]
Thanks @SallyPickard ! Could you uplaod the test script into the test library please?
https://burohappold.sharepoint.com/:f:/s/BHoM/Eg4R87DAQFFDstDSfHoBW1YBE4x2hB7KFMRmHyn6SevtRA?e=BVUcZt

**Comment by SallyPickard** [comment]
Done! 😊

Façade Engineer
BuroHappold Engineering | Façade Engineering
07803 029333
+44 (0)20 7927 9700
www.burohappold.com<http://www.burohappold.com/> | LinkedIn<http://j.mp/bhLIprofile> | Twitter<http://buro.im/bhontwitter> | Instagram<http://buro.im/burogram>
[40-Year-Anniversary-Footer-2.png]

**Comment by enarhi** [comment]
Renaming this issue to reflect its relevance to proper header functionality in general, with support for header objects, a header type enum, and header get implementation.
