### ISSUE TITLE
Remove use of CustomData in the code

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/HTTP_Toolkit#57]
The files listed below have been detected as having code using `CustomData`. This detection has been automatic, and may have picked up on code comments or documentation. Please review each file carefully and remove all instances of `CustomData`.

This should be completed by the 30th October 2020.

<details>
<summary>Full list</summary>
<p>

 - [ ] HTTP_Toolkit\HTTP_Engine\Compute\GetRequestAsync.cs

 - [ ] HTTP_Toolkit\HTTP_Engine\Convert\ToUrlString.cs

 - [ ] HTTP_Toolkit\HTTP_Engine\Create\GetRequest.cs

</p>
</details>

**Comment by enarhi** [comment]
As noted in the linked issue by @rolyhudson the CustomData usage here is a result of parsing of custom objects, and will be renamed to whatever @adecler names it in the corresponding BHoM issue once that issue is resolved.

**Comment by FraserGreenroyd** [comment]
Since determined not to rename custom data is usage in this toolkit is valid.
