### ISSUE TITLE
HTTP_Toolkit: ToUrlString fails if the value is not a string

### ISSUE THREAD

**Issue by epignatelli** [BHoM/HTTP_Toolkit#9]
#### Description:

The code below fails if `pair.Value` is not a `string`, specifically because `pair.Value as string` returns `null`.
```
        public static string ToUrlString(Dictionary<string, object> data)
        {
            List<string> url = new List<string>();
            foreach (KeyValuePair<string, object> pair in data)
            {
                url.Add($"{pair.Key}={pair.Value as string}");
            }
            return string.Join("&", url);
        }
```

#### How to replicate:

You can use the test file

#### Expected behaviour:

If a meaningful `string` representation of the object can be created, that's the one that shoul 

#### Test file(s):

[DownloadData.zip](https://github.com/BHoM/HTTP_Toolkit/files/3546989/DownloadData.zip)

**Comment by epignatelli** [comment]
Solving this in 3.1, since there has been no space to solve it in 3.0.

**Comment by enarhi** [comment]
This is also an issue for values that can be cast to strings but need different behavior, such as a string array that is to be passed to a single parameter (ie field1=value1&field1=value2&field1=value3).
